services:
  - type: web
    name: sppu-ai-study-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
